version: "2"

services:
  master:
    container_name: node_master
    build: ./master
    image: master
    ports:
      - 3000:3000
    volumes:
      - ./master:/usr/src/app
    depends_on:
      - mongo
      - redis

  worker:
    container_name: node_worker
    build: ./worker
    image: worker
    volumes:
      - ./worker:/usr/src/app
    depends_on:
      - redis
      - mongo

  mongo:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
